backend:
  name: git-gateway
  branch: main # Verifique se sua branch é 'main' ou 'master'

local_backend: true # Permite testar no Firebase Studio

media_folder: "assets/img/noticias"
public_folder: "/assets/img/noticias"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Capa", name: "image", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
